### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by some-du6e** [notzastix/BlooketCheatTools#6]
i was trying my hack and then this happened
![Screen Shot 2022-06-16 at 1 35 22 PM](https://user-images.githubusercontent.com/103129948/174150745-4f950082-ff83-4215-8e72-31587b85310a.png)

it tried to report me lmao 
and also how do i fix this?
![Screen Shot 2022-06-16 at 1 36 53 PM](https://user-images.githubusercontent.com/103129948/174150861-5133220d-0c8c-40e3-9974-79fe7a241bed.png)

(im trying to make a multitool btw)

**Comment by notzastix** [comment]
its not reporting you, its because your accessing a website not allowed by blooket, (etc: "blooket.com" and its subdomains)
